POST http://127.0.0.1:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
  "first_name": "Dr. Johny",
  "last_name":"Sins",
  "username": "sins1253",
  "phone_number": "1050101010",
  "employee_id":"brazers001",
  "password": "dani435@",
  "confirm_password":"dani435@"
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "phone_number":"9090909090",
    "password":"chips1234"
}

###

POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MTA2MTgxMCwiaWF0IjoxNzYwNDU3MDEwLCJqdGkiOiI2NmY0YjUzNzFmOTg0NWZmODY2M2JhYzg1ZjE4YWI4OSIsInVzZXJfaWQiOjV9.3Ghn8rHsSIdiYD6ALPDc5mrQX9DSEzKzjVVdAWYtnko"
}

###
POST http://127.0.0.1:8000/api/addpatients/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMDY0MjkyLCJpYXQiOjE3NjEwNjA2OTIsImp0aSI6ImY4Y2Q2NGNiMDJiYTQxZmRhY2ZkYTEyZDYxYmE3ZDkwIiwidXNlcl9pZCI6MTd9.KmutVVQZUsUi-05y4CRycqNtZpgF58U7GmQQib-bUpk

{
  "name":"Pathna",
  "age":"20",
  "gender":"M",
  "weight_kg":"100",
  "height_cm":"175"
}
###

GET http://127.0.0.1:8000/api/patients/32/visits/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMDY0Mzg3LCJpYXQiOjE3NjEwNjA3ODcsImp0aSI6IjVmODRmNTcwMGY0OTRmYTI5NDUyZjgyMjc3MjI2M2M2IiwidXNlcl9pZCI6MTd9.oRuVEOK0ov6t-s5oRjCVTaJi6JWIkAhE2lk58ovgUBo


###
POST http://127.0.0.1:8000/api/patients/28/visits/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNzMxNjAwLCJpYXQiOjE3NjA3MjgwMDAsImp0aSI6IjMxN2JhNzA3ZTliZTRhNDM5MTJiZjYwZjU4YWVkMzljIiwidXNlcl9pZCI6MTV9.RrpilZnsWm2R9-pUUn2Q-qTmrKY9Jx57SV-yqaHVAvU

{
  "diagnosis": "Fever",
  "treatment": "Rest and hydration",
  "test": "Blood test"
}

###

POST http://127.0.0.1:8000/api/patients/28/visits/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNzMxNjAwLCJpYXQiOjE3NjA3MjgwMDAsImp0aSI6IjMxN2JhNzA3ZTliZTRhNDM5MTJiZjYwZjU4YWVkMzljIiwidXNlcl9pZCI6MTV9.RrpilZnsWm2R9-pUUn2Q-qTmrKY9Jx57SV-yqaHVAvU


###
GET http://127.0.0.1:8000/api/addpatients/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMDY0Mzg3LCJpYXQiOjE3NjEwNjA3ODcsImp0aSI6IjVmODRmNTcwMGY0OTRmYTI5NDUyZjgyMjc3MjI2M2M2IiwidXNlcl9pZCI6MTd9.oRuVEOK0ov6t-s5oRjCVTaJi6JWIkAhE2lk58ovgUBo
###
PUT http://127.0.0.1:8000/api/patients/20/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNjQ3NDU1LCJpYXQiOjE3NjA2NDM4NTUsImp0aSI6IjFlMTZiZTI4MzM5MjQ3YWNhMzA0MTRhMWMzNTVhNTlhIiwidXNlcl9pZCI6MTV9.--QIckpdvw3P6__QEPYMPZojCO2-0x2HFRDHW13C2wQ

{
  "name":"Hello",
  "age":"20",
  "gender":"M",
  "weight_kg":"100",
  "height_cm":"175"
}


###
DELETE http://127.0.0.1:8000/api/delete/patient/visit/26/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMDY0Mzg3LCJpYXQiOjE3NjEwNjA3ODcsImp0aSI6IjVmODRmNTcwMGY0OTRmYTI5NDUyZjgyMjc3MjI2M2M2IiwidXNlcl9pZCI6MTd9.oRuVEOK0ov6t-s5oRjCVTaJi6JWIkAhE2lk58ovgUBo